server:
  port: 6061
  servlet:
    context-path: /ssoa
    session:
      timeout: "PT30M"

swagger:
  enabled: true

hostAddress:
  ip: http://localhost:6061/ssoa
  exitUrl: /user/logout
    
sso:
  path: http://localhost:6065/ssocenter
  login: /index.html
  isLogin: /sso/isLogin
  tokenCheck: /sso/tokenCheck
  exit: /sso/exit
  sysName: ssoa

